#!/bin/sh

# Support Ubuntu ARM C compiler
export	CROSS_COMPILE?=/usr/bin/arm-linux-gnueabi-


rm	-f	binaries/*
rm	-rf	log
rm	-fr	result

mkdir	-p	log
mkdir	-p	result/FAIL
mkdir	-p	result/OK
mkdir	-p	result/binaries
mkdir	-p	result
mkdir	-p	result/map
mkdir	-p	result/elf

source	./mk-config-list.sh

build ()
{
	make distclean
	make $1_defconfig
	make > log/$1.log 2>&1 || mv log/$1.log result/FAIL/$1.log.FAIL
	mv log/$1.log result/OK/$1.log.OK	|| echo
	mv binaries/*.elf	result/elf
	mv binaries/*.map	result/map
	mv binaries/*.bin	result/binaries
}

build_all ()
{
	for f in `cat $CONFIG_LIST` ; do
		build	$f
	done
}

build_all

echo
echo
echo "### Done!"

